# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66a4aa9c060bf4a5a19e2fb1ae1503ca950ea8f8a87449b2a665fd7619b81b96e6ea9f5893d1d69b40677f30b0ee0104171c22379404678de183dac76116a7c1

test:
  secret_key_base: eab850ee0e0e1940e5e8d0a3fcd9f07a1a9d5227bd741fd9adcfb70f69ad5deb9041a9636122c2a56c3934e70a487c59abeb4170945f052f474ec194f09f0d56

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
